### ISSUE TITLE
Issue to use gtfsdb with mysql

### ISSUE THREAD

**Issue by p4535992** [OpenTransitTools/gtfsdb#12]
Hi, sorry to bother you, i just start to use python and i want to try out gtfsdb but i must miss something on the command line:
`bin\gtfsdb-load --database_url jdbc:mysql://localhost:3306/ file:///C:/Users/Utente/Desktop/ac-transit_20150218_1708.zip`

Is very similar to a past issue  but i'm just stuck whit that, so forgive me if the error is patently stupid.

The error i get is:

> Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\gtfsdb\bin\gtfsdb-load-script.py", line 13, in <module>
    sys.exit(gtfsdb.scripts.gtfsdb_load())
  File "c:\users\utente\desktop\gtfsdb\gtfsdb\scripts.py", line 10, in gtfsdb_load
    database_load(args.file, **kwargs)
  File "c:\users\utente\desktop\gtfsdb\gtfsdb\api.py", line 16, in database_load
    db = Database(**kwargs)
  File "c:\users\utente\desktop\gtfsdb\gtfsdb\model\db.py", line 21, in __init__
    self.url = kwargs.get('url', config.DEFAULT_DATABASE_URL)
  File "c:\users\utente\desktop\gtfsdb\gtfsdb\model\db.py", line 96, in url
    self.engine = create_engine(val)
  File "c:\users\utente\desktop\gtfsdb\eggs\sqlalchemy-1.0.12-py2.7.egg\sqlalchemy\engine\__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "c:\users\utente\desktop\gtfsdb\eggs\sqlalchemy-1.0.12-py2.7.egg\sqlalchemy\engine\strategies.py", line 49, in create
    u = url.make_url(name_or_url)
  File "c:\users\utente\desktop\gtfsdb\eggs\sqlalchemy-1.0.12-py2.7.egg\sqlalchemy\engine\url.py", line 186, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "c:\users\utente\desktop\gtfsdb\eggs\sqlalchemy-1.0.12-py2.7.egg\sqlalchemy\engine\url.py", line 235, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name)
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'jdbc:mysql://localhost:3306/'

TY in advance for any help.

**Comment by mileserickson** [comment]
Check your database URL. Python does not use JDBC. You need to use something more like this:
* `--database_url mysql://$USERNAME:$PASSWORD@localhost/$DBNAME`

More info about database URLs in SQLAlchemy can be found here:
* http://docs.sqlalchemy.org/en/rel_1_0/core/engines.html

**Comment by fpurcell** [comment]
As Miles pointed out, jdbc (Java DB connection) shouldn't be in your database url.  Thanks for answering, Miles.
