### ISSUE TITLE
db support -- sqlite: crashing on a feed with utf-8 route names w/python 2.7.

### ISSUE THREAD

**Issue by Littlericket** [OpenTransitTools/gtfsdb#14]
I've encountered this error while imporing the german VBB gtfs data from http://daten.berlin.de/datensaetze/vbb-fahrplandaten-april-bis-dezember-2016

The tool also crashes completely when using mysql because VBB has many empty columns which are not taken care of

```
13:54:21,280 DEBUG [gtfsdb.model.route] RouteType.load (1 seconds)
13:54:21,702 DEBUG [gtfsdb.model.route] RouteFilter.load (0 seconds)
13:54:21,702 DEBUG [gtfsdb.model.feed_info] FeedInfo.load (0 seconds)
Traceback (most recent call last):
  File "bin/gtfsdb-load", line 14, in <module>
    sys.exit(gtfsdb.scripts.gtfsdb_load())
  File "/opt/gtfsdb/gtfsdb/scripts.py", line 10, in gtfsdb_load
    database_load(args.file, **kwargs)
  File "/opt/gtfsdb/gtfsdb/api.py", line 19, in database_load
    gtfs.load(db, **kwargs)
  File "/opt/gtfsdb/gtfsdb/model/gtfs.py", line 34, in load
    cls.load(db, **load_kwargs)
  File "/opt/gtfsdb/gtfsdb/model/base.py", line 143, in load
    db.engine.execute(table.insert(), records)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1991, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 914, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 200, in raise_from_cause
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1116, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 447, in do_executemany
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. [SQL: u'INSERT INTO agency (agency_id, agency_name, agency_url, agency_timezone, agency_lang, agency_phone) VALUES (?, ?, ?, ?, ?, ?)'] [parameters: (('VBB', 'Verkehrsverbund Brandenburg-Berlin', 'http://www.vbb.de', 'Europe/Berlin', 'de', None), ('ANG---', 'G\xc3\xbcnter Anger G\xc3\xbcterverkehrs GmbH & Co. Omnibusvermietung KG', 'http://www.anger-busvermietung.de', 'Europe/Berlin', 'de', '033208 22010'), ('BEH---', 'Fritz Behrendt OHG', 'http://www.behrendt-touristik.de', 'Europe/Berlin', 'de', '0331 7491400'), ('BMO---', 'Busverkehr M\xc3\xa4rkisch-Oderland GmbH', 'http://www.busmol.de', 'Europe/Berlin', 'de', '03341 478383'), ('BON---', 'Busverkehr Oder-Spree GmbH', 'http://www.bos-fw.de', 'Europe/Berlin', 'de', '03361 556133'), ('BRB---', 'Verkehrsbetriebe Brandenburg an der Havel GmbH', 'http://www.vbbr.de', 'Europe/Berlin', 'de', '03381 5340'), ('BRT---', 'Verkehrsbetriebe Brandenburg an der Havel GmbH', 'http://www.vbbr.de', 'Europe/Berlin', 'de', '03381 5340'), ('BTS___', 'Barnimer Busgesellschaft mbH', 'http://www.bbg-eberswalde.de', 'Europe/Berlin', 'de', '03334 235003')  ... displaying 10 of 60 total bound parameter sets ...  ('WEZ---', 'Wetzel', 'http://www.wetzel-cammer.de', 'Europe/Berlin', 'de', '033835 228'), ('WS----', 'Woltersdorfer Stra\xc3\x9fenbahn GmbH', 'http://www.woltersdorfer-strassenbahn.com', 'Europe/Berlin', 'de', '03362 881230'))]
```

**Comment by tsimokhin** [comment]
Similar problem here.
```
22:15:40,064 DEBUG [gtfsdb.model.route] RouteType.load (0 seconds)
22:15:40,320 DEBUG [gtfsdb.model.stop_feature] StopFeatureType.load (0 seconds)
22:15:40,320 DEBUG [gtfsdb.model.feed_info] FeedInfo.load (0 seconds)
Traceback (most recent call last):
  File "/usr/local/bin/gtfsdb-load", line 9, in <module>
    load_entry_point('gtfsdb==0.1.5', 'console_scripts', 'gtfsdb-load')()
  File "/usr/local/lib/python2.7/dist-packages/gtfsdb/scripts.py", line 33, in gtfsdb_load
    database_load(args.file, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gtfsdb/api.py", line 21, in database_load
    gtfs.load(db, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gtfsdb/model/gtfs.py", line 34, in load
    cls.load(db, **load_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gtfsdb/model/base.py", line 83, in load
    db.engine.execute(table.insert(), records)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1986, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1339, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pysqlite2.dbapi2.ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. [SQL: u'INSERT INTO agency (agency_id, agency_name, agency_url, agency_timezone, agency_lang, agency_phone) VALUES (?, ?, ?, ?, ?, ?)'] [parameters: ('klaipeda', 'Klaip\xc4\x97dos keleivinis transportas', 'http://www.klaipedatransport.lt', 'Europe/Vilnius', 'lt', '8 800 12344')]
```

**Comment by vmarci21** [comment]
```
21:06:38,882 DEBUG [gtfsdb.model.calendar] Calendar.load (0 seconds)
21:06:38,991 DEBUG [gtfsdb.model.calendar] CalendarDate.load (0 seconds)
Traceback (most recent call last):
  File "/usr/local/bin/gtfsdb-load", line 9, in <module>
    load_entry_point('gtfsdb', 'console_scripts', 'gtfsdb-load')()
  File "/media/vmarci21/User data/vmarci/Downloads/gtfsdb-master/gtfsdb/scripts.py", line 10, in gtfsdb_load
    database_load(args.file, **kwargs)
  File "/media/vmarci21/User data/vmarci/Downloads/gtfsdb-master/gtfsdb/api.py", line 19, in database_load
    gtfs.load(db, **kwargs)
  File "/media/vmarci21/User data/vmarci/Downloads/gtfsdb-master/gtfsdb/model/gtfs.py", line 34, in load
    cls.load(db, **load_kwargs)
  File "/media/vmarci21/User data/vmarci/Downloads/gtfsdb-master/gtfsdb/model/base.py", line 141, in load
    db.engine.execute(table.insert(), records)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 2052, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 947, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 262, in _execute_on_connection
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1055, in _execute_clauseelement
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1191, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1386, in _handle_dbapi_exception
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 202, in raise_from_cause
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1161, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 459, in do_executemany
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. [SQL: u'INSERT INTO routes (route_id, agency_id, route_short_name, route_long_name, route_desc, route_type, route_url, route_color, route_text_color) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (('1', '2', '1', 'Szeged Plaza / Szeged p\xc3\xa1lyaudvar', None, '0', None, 'FFFF00', '000000'), ('2', '2', '10', 'Tarj\xc3\xa1n, V\xc3\xadztorony t\xc3\xa9r / Klinik\xc3\xa1k', None, '800', None, '00CC00', 'FFFFFF'), ('4', '1', '13', 'Tarj\xc3\xa1n, V\xc3\xadztorony t\xc3\xa9r / M\xc3\xb3rav\xc3\xa1ros', 'Forgalmi terel\xc3\xa9s M\xc3\xb3rav\xc3\xa1rosban 10.02.-11.15. k\xc3\xb6z\xc3\xb6tt!', '3', None, '0000FF', 'FFFFFF'), ('5', '1', '13A', 'Mars t\xc3\xa9r / M\xc3\xb3rav\xc3\xa1ros', 'Forgalmi terel\xc3\xa9s M\xc3\xb3rav\xc3\xa1rosban 10.02.-11.15. k\xc3\xb6z\xc3\xb6tt!', '3', None, '0000FF', 'FFFFFF'), ('6', '2', '19', 'Makkosh\xc3\xa1z / Tarj\xc3\xa1n, V\xc3\xadztorony t\xc3\xa9r', None, '800', None, '00CC00', 'FFFFFF'), ('7', '2', '2', 'Eur\xc3\xb3pa liget / Szeged p\xc3\xa1lyaudvar', None, '0', None, 'FFFF00', '000000'), ('8', '1', '20', 'Pet\xc5\x91fitelep, F\xc5\x91 t\xc3\xa9r / Als\xc3\xb3v\xc3\xa1ros, Vadkerti t\xc3\xa9r', None, '3', None, '0000FF', 'FFFFFF'), ('9', '1', '20A', 'Pet\xc5\x91fitelep, F\xc5\x91 t\xc3\xa9r / Honv\xc3\xa9d t\xc3\xa9r', None, '3', None, '0000FF', 'FFFFFF')  ... displaying 10 of 43 total bound parameter sets ...  ('43', '1', 'Auchan', 'Auchan / Fels\xc5\x91v\xc3\xa1ros / Auchan', 'A j\xc3\xa1ratok ig\xc3\xa9nybev\xc3\xa9tele d\xc3\xadjmentes.', '3', 'http://dakk.hu/images/Auchan%20menetren%20m%c3%b3dos%c3%adt%c3%a1s%20utast%c3%a1j%c3%a9koztat%c3%b3.pdf', '0000FF', 'FFFFFF'), ('44', '1', '12', 'Tarj\xc3\xa1n / Belv\xc3\xa1rosi temet\xc5\x91 / Tarj\xc3\xa1n', 'Temet\xc5\x91i j\xc3\xa1rat', '3', None, '0000FF', 'FFFFFF'))]

```

**Comment by fpurcell** [comment]
If anyone has a fix to this problem, please submit a pull request.

**Comment by detman** [comment]
same problem here:
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. [SQL: u'INSERT INTO agency (agency_id, agency_name, agency_url, agency_timezone, agency_lang, agency_phone) VALUES (?, ?, ?, ?, ?, ?)'] [parameters: ('ANG---', 'G\xc3\xbcnter Anger G\xc3\xbcterverkehrs GmbH & Co. Omnibusvermietung KG', 'http://www.anger-busvermietung.de', 'Europe/Berlin', 'de', '033208 22010')]
