### ISSUE TITLE
On Windows, need to run buildout multiple times (it intermittently crashes) before all dependencies are downloaded

### ISSUE THREAD

**Issue by KayJay89** [OpenTransitTools/gtfsdb#23]
Hi all,

Been struggling for couple days to get this working but I am failing each time and running out of answers. I can't seem to get the buildout to run properly:

> (try) C:\gtfs\gtfsdb>buildout install prod
Develop: 'C:\\gtfs\\gtfsdb\\.'
c:\gtfs\try\lib\site-packages\setuptools\dist.py:352: UserWarning: Normalizing '0.1.6dev' to '0.1.6.dev0'
  normalized_version,
Installing prod.
Getting distribution for 'geoalchemy2>=0.2.4'.
While:
  Installing prod.
  Getting distribution for 'geoalchemy2>=0.2.4'.
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "c:\gtfs\try\lib\site-packages\zc.buildout-2.9.4-py2.7.egg\zc\buildout\buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "c:\gtfs\try\lib\site-packages\zc.buildout-2.9.4-py2.7.egg\zc\buildout\buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "c:\gtfs\try\lib\site-packages\zc.buildout-2.9.4-py2.7.egg\zc\buildout\buildout.py", line 1553, in _call
    return f()
  File "c:\gtfs\gtfsdb\eggs\zc.recipe.egg-2.0.3-py2.7.egg\zc\recipe\egg\egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "c:\gtfs\gtfsdb\eggs\zc.recipe.egg-2.0.3-py2.7.egg\zc\recipe\egg\egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "c:\gtfs\try\lib\site-packages\zc.buildout-2.9.4-py2.7.egg\zc\buildout\easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "c:\gtfs\try\lib\site-packages\zc.buildout-2.9.4-py2.7.egg\zc\buildout\easy_install.py", line 714, in install
    for dist in self._get_dist(req, ws):
  File "c:\gtfs\try\lib\site-packages\zc.buildout-2.9.4-py2.7.egg\zc\buildout\easy_install.py", line 563, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "c:\gtfs\try\lib\site-packages\zc.buildout-2.9.4-py2.7.egg\zc\buildout\easy_install.py", line 1730, in _move_to_eggs_dir_and_compile
    assert newdist is not None  # newloc above is missing our dist?!
AssertionError

**Comment by KayJay89** [comment]
After tinkering a bit more I found a solution that worked for me. Bear in mind I'm using a virtual env. I followed every step however before running buildout, I ran setup.py. 

Is that normal behaviour or am I still doing something wrong in one of the steps?

**Comment by mwferris** [comment]
i also am having this problem installing on Windows. I ran "buildout install prod postgresql" like @KayJay89  and it seems to have worked now...

**Comment by fpurcell** [comment]
This shouldn't be the case, and it wasn't the case in years past.  That said, I've recently seen similar issues on Windows.  Ever since upgrading setup tools and buildout (needed newer versions for recent pypi https fixes), I've seen that buildout intermittently dies on loading dependencies.  My current work-around is to just re-run buildout, and eventually get a working buildout.   Not sure these problems are due to something in gtfsdb's setup.py or buildout.cfg.

**Comment by fpurcell** [comment]
Going to close this issue in favor of #67 (move to puppet).
