### ISSUE TITLE
IOError at urllib.urlretrieve because of missing protocol identifier file:///

### ISSUE THREAD

**Issue by patrickj0607** [OpenTransitTools/gtfsdb#33]
While trying to load zipped GTFS data, as follow:

```
gtfsdb-load.exe --database_url postgresql://user:pass@localhost:5432/gtfs --is_geospatial "D:\work\projects\gtfs\gtfsdata.zip"
```
I receive an error message caused by urllib's ``urlretrieve`` method:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Patrick\Anaconda3\envs\py27\lib\urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "C:\Users\Patrick\Anaconda3\envs\py27\lib\urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "C:\Users\Patrick\Anaconda3\envs\py27\lib\urllib.py", line 210, in open
    return self.open_unknown(fullurl, data)
  File "C:\Users\Patrick\Anaconda3\envs\py27\lib\urllib.py", line 222, in open_unknown
    raise IOError, ('url error', 'unknown url type', type)
IOError: [Errno url error] unknown url type: 'd'
```

However, if I preappend ``file:///`` to the filename in ``gtfs.py``, everything runs smoothly:

```
    def __init__(self, filename):
        self.file = filename
        print filename    # "D:\work\projects\gtfs\gtfsdata.zip"
        self.local_file = urlretrieve("file:///" + filename)[0]  # only for demonstration purposes
```
Is this really a bug?

**Comment by BakuCity** [comment]
For me on win local zip loads with `self.local_file = filename`
So, I have this piece replaced with:
```
if '://' in filename:
    self.local_file = urlretrieve(filename)[0]
else:
    self.local_file = filename
```
Dunno about other platforms.
