### ISSUE TITLE
Error using gtfsdb-load

### ISSUE THREAD

**Issue by aborruso** [OpenTransitTools/gtfsdb#6]
Hi,
when I run
`gtfsdb-load  --database_url sqlite:///db.sqlite --is_geospatial http://www.comune.palermo.it/gtfs/amat_feed_gtfs_v7.zip `

I have this error:
Traceback (most recent call last):
  File "/usr/local/bin/gtfsdb-load", line 9, in <module>
    load_entry_point('gtfsdb==0.1.5', 'console_scripts', 'gtfsdb-load')()
  File "/usr/local/lib/python2.7/dist-packages/gtfsdb/scripts.py", line 33, in gtfsdb_load
    database_load(args.file, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gtfsdb/api.py", line 18, in database_load
    db = Database(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gtfsdb/model/db.py", line 21, in __init__
    config.DEFAULT_IS_GEOSPATIAL)
  File "/usr/local/lib/python2.7/dist-packages/gtfsdb/model/db.py", line 56, in is_geospatial
    cls.add_geometry_column()
  File "/usr/local/lib/python2.7/dist-packages/gtfsdb/model/route.py", line 98, in add_geometry_column
    from geoalchemy import GeometryColumn, GeometryDDL, MultiLineString
  File "/usr/local/lib/python2.7/dist-packages/geoalchemy/__init__.py", line 2, in <module>
    from geoalchemy.base import *
  File "/usr/local/lib/python2.7/dist-packages/geoalchemy/base.py", line 242, in <module>
    class SpatialComparator(ColumnProperty.ColumnComparator):
AttributeError: type object 'ColumnProperty' has no attribute 'ColumnComparator'

Some tips to solve. 

Thank you very much

**Comment by fpurcell** [comment]
Try this: bin/gtfsdb-load --database_url sqlite:///db.sqlite http://www.comune.palermo.it/gtfs/amat_feed_gtfs_v7.zip

NOTE: the --is_geospatial flag is something will only work on a geospatial database like PostGIS.

**Comment by aborruso** [comment]
Yes, it works. It would be great to have a sqlite spatial file.
I will use postgis.

Thank you
